services:
  acme-keycloak:
    image: quay.io/keycloak/keycloak
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
    environment:
      DB_VENDOR: "h2"
      KEYCLOAK_THEME_CACHING: "false"
      KEYCLOAK_THEME_TEMPLATE_CACHING: "false"
      PROXY_ADDRESS_FORWARDING: "true"
# force usage for standalone.xml for local dev
      KEYCLOAK_CONFIG_FILE: "standalone.xml"
# Exposes Metrics via http://localhost:9990/metrics
      KEYCLOAK_STATISTICS: all
      JAVA_OPTS: "-XX:MaxRAMPercentage=80 -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -Djava.net.preferIPv4Stack=true -XX:FlightRecorderOptions=stackdepth=256"
    mem_limit: 1024m
    mem_reservation: 1024m
    cpus: 2

    command:
      - "-Dwildfly.statistics-enabled=true"
    extra_hosts:
      - "id.acme.test:172.17.0.1"
      - "apps.acme.test:172.17.0.1"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8790:8790"
      - "9990:9990"
      - "127.0.0.1:8787:8787"